name: ci-sonarcloud
on:
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - run: go test -coverprofile=coverage ./go
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
        SONAR_PROJECT_KEY: GuiFreitasTT_golang-sonar
        SONAR_ORGANIZATION: Gui
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       


